name: Retrain Model CI

on:
  push:
    branches: [ main ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install mlflow dagshub scikit-learn pandas numpy imbalanced-learn lightgbm

      - name: Run Model Training
        run: |
          python MLProject/modelling.py

      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: MLProject/mlruns/

      - name: Build and Push Docker Image
        run: |
          mlflow models build-docker -m MLProject/mlruns/0/<RUN_ID>/artifacts/model -n fxsal/ecommerce-ml-model:latest
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push fxsal/ecommerce-ml-model:latest
