name: Retrain Model CI

on:
  push:
    branches: [ main ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install mlflow dagshub scikit-learn pandas numpy imbalanced-learn lightgbm

      - name: Run Model Training
        env:
          DAGSHUB_TOKEN: 59ba3d1394b9f8ff7c64ff46a56c8d71ebdab563
        run: |
          echo "Mulai training model dan logging ke DagsHub..."
          python MLProject/modelling.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: MLProject/mlruns/

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: faisals21
          DOCKERHUB_TOKEN: dckr_pat_Vq493Jd5xk_sxHfLz-UGW3BDGKk
        run: |
          echo "Mulai build Docker image dari model MLflow..."
          mlflow models build-docker -m MLProject/mlruns/0/bb66aabb00c2439f95d47c006ada62d7/artifacts/model -n faisals21/ecommerce-ml-model:latest
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push faisals21/ecommerce-ml-model:latest
